export const patientsData = [
	{
		image: '/assets/images/avatar/user-1.png',
		date: '05 May, 2024',
		name: 'John Doe',
		email: 'john@example.com',
		phoneNumber: '+1 555 123 4567',
		insurance: 'Yes',
		location: 'Algeria',
		treatmentType: 'Cardiology',
		doctorName: 'Dr. Michael',
		gender: 'Male'
	},
	{
		image: '/assets/images/avatar/user-2.png',
		date: '12 May, 2024',
		name: 'Jane Smith',
		email: 'jane@example.com',
		phoneNumber: '+44 20 7946 0958',
		insurance: 'No',
		location: 'Argentina',
		treatmentType: 'Dermatology',
		doctorName: 'Dr. Sarah',
		gender: 'Female'
	},
	{
		image: '/assets/images/avatar/user-3.png',
		date: '19 June, 2024',
		name: 'Alice Johnson',
		email: 'alice@example.com',
		phoneNumber: '+61 2 9374 4000',
		insurance: 'No',
		location: 'Belgium',
		treatmentType: 'Neurology',
		doctorName: 'Dr. Robert',
		gender: 'Female'
	},
	{
		image: '/assets/images/avatar/user-4.png',
		date: '09 Feb, 2024',
		name: 'Robert Brown',
		email: 'robert@example.com',
		phoneNumber: '+49 30 123456',
		insurance: 'Yes',
		location: 'Mexico',
		treatmentType: 'Orthopedics',
		doctorName: 'Dr. Emily',
		gender: 'Male'
	},
	{
		image: '/assets/images/avatar/user-5.png',
		date: '28 Jan, 2024',
		name: 'Emily Davis',
		email: 'emily@example.com',
		phoneNumber: '+33 1 42 68 53 00',
		insurance: 'Yes',
		location: 'Russia',
		treatmentType: 'Pediatrics',
		doctorName: 'Dr. James',
		gender: 'Female'
	},
	{
		image: '/assets/images/avatar/user-6.png',
		date: '23 June, 2024',
		name: 'Michael Wilson',
		email: 'michael@example.com',
		phoneNumber: '+34 91 123 45 67',
		insurance: 'Yes',
		location: 'Denmark',
		treatmentType: 'Gastroenterology',
		doctorName: 'Dr. Olivia',
		gender: 'Male'
	},
	{
		image: '/assets/images/avatar/user-7.png',
		date: '16 Dec, 2023',
		name: 'Sarah Moore',
		email: 'sarah@example.com',
		phoneNumber: '+81 3 1234 5678',
		insurance: 'Yes',
		location: 'Sudan',
		treatmentType: 'Oncology',
		doctorName: 'Dr. David',
		gender: 'Female'
	},
	{
		image: '/assets/images/avatar/user-8.png',
		date: '06 Sep, 2024',
		name: 'James Taylor',
		email: 'james@example.com',
		phoneNumber: '+91 22 1234 5678',
		insurance: 'No',
		location: 'Spain',
		treatmentType: 'Urology',
		doctorName: 'Dr. Sophia',
		gender: 'Male'
	},
	{
		image: '/assets/images/avatar/user-9.png',
		date: '21 Nov, 2023',
		name: 'Laura Anderson',
		email: 'laura@example.com',
		phoneNumber: '+7 495 123-45-67',
		insurance: 'Yes',
		location: 'Germany',
		treatmentType: 'General Medicine',
		doctorName: 'Dr. William',
		gender: 'Female'
	},
	{
		image: '/assets/images/avatar/user-10.png',
		date: '10 March, 2024',
		name: 'David Thomas',
		email: 'david@example.com',
		phoneNumber: '+55 11 1234-5678',
		insurance: 'No',
		location: 'Israel',
		treatmentType: 'Cardiology',
		doctorName: 'Dr. Charlotte',
		gender: 'Male'
	},
	{
		image: '/assets/images/avatar/user-11.png',
		date: '17 March, 2024',
		name: 'Jessica Lee',
		email: 'jessica@example.com',
		phoneNumber: '+27 11 123 4567',
		insurance: 'No',
		location: 'Denmark',
		treatmentType: 'Dermatology',
		doctorName: 'Dr. Henry',
		gender: 'Female'
	},
	{
		image: '/assets/images/avatar/user-12.png',
		date: '27 Feb, 2024',
		name: 'Daniel Martin',
		email: 'daniel@example.com',
		phoneNumber: '+65 6 1234 567',
		insurance: 'Yes',
		location: 'Russia',
		treatmentType: 'Neurology',
		doctorName: 'Dr. Mia',
		gender: 'Male'
	},
	{
		image: '/assets/images/avatar/user-13.png',
		date: '22 June, 2024',
		name: 'Sophia Harris',
		email: 'sophia@example.com',
		phoneNumber: '+39 06 123 4567',
		insurance: 'No',
		location: 'Mexico',
		treatmentType: 'Orthopedics',
		doctorName: 'Dr. Benjamin',
		gender: 'Female'
	},
	{
		image: '/assets/images/avatar/user-14.png',
		date: '19 June, 2024',
		name: 'Matthew Clark',
		email: 'matthew@example.com',
		phoneNumber: '+52 55 1234 5678',
		insurance: 'Yes',
		location: 'Namibia',
		treatmentType: 'Pediatrics',
		doctorName: 'Dr. Ava',
		gender: 'Male'
	},
	{
		image: '/assets/images/avatar/user-15.png',
		date: '21 June, 2024',
		name: 'Olivia Lewis',
		email: 'olivia@example.com',
		phoneNumber: '+86 10 1234 5678',
		insurance: 'Yes',
		location: 'Brazil',
		treatmentType: 'Gastroenterology',
		doctorName: 'Dr. Jackson',
		gender: 'Female'
	},
	{
		image: '/assets/images/avatar/user-16.png',
		date: '14 June, 2024',
		name: 'Andrew Walker',
		email: 'andrew@example.com',
		phoneNumber: '+31 20 123 4567',
		insurance: 'Yes',
		location: 'Brazil',
		treatmentType: 'Oncology',
		doctorName: 'Dr. Harper',
		gender: 'Male'
	},
	{
		image: '/assets/images/avatar/user-17.png',
		date: '14 July, 2024',
		name: 'Amelia Hall',
		email: 'amelia@example.com',
		phoneNumber: '+46 8 123 4567',
		insurance: 'No',
		location: 'Poland',
		treatmentType: 'Urology',
		doctorName: 'Dr. Ethan',
		gender: 'Female'
	},
	{
		image: '/assets/images/avatar/user-18.png',
		date: '08 July, 2024',
		name: 'William Allen',
		email: 'william@example.com',
		phoneNumber: '+64 9 123 4567',
		insurance: 'No',
		location: 'Russia',
		treatmentType: 'General Medicine',
		doctorName: 'Dr. Evelyn',
		gender: 'Male'
	},
	{
		image: '/assets/images/avatar/user-19.png',
		date: '13 July, 2024',
		name: 'Mia Young',
		email: 'young@example.com',
		phoneNumber: '+45 12 34 56 78',
		insurance: 'Yes',
		location: 'Serbia',
		treatmentType: 'Cardiology',
		doctorName: 'Dr. Jack',
		gender: 'Female'
	},
	{
		image: '/assets/images/avatar/user-20.png',
		date: '25 July, 2024',
		name: 'Henry King',
		email: 'henry@example.com',
		phoneNumber: '+41 21 123 45 67',
		insurance: 'Yes',
		location: 'Argentina',
		treatmentType: 'Dermatology',
		doctorName: 'Dr. Ella',
		gender: 'Male'
	},
	{
		image: '/assets/images/avatar/user-21.png',
		date: '02 Aug, 2024',
		name: 'Charlotte Wright',
		email: 'charlotte@example.com',
		phoneNumber: '+1 604 123 4567',
		insurance: 'Yes',
		location: 'Malaysia',
		treatmentType: 'Neurology',
		doctorName: 'Dr. Logan',
		gender: 'Female'
	},
	{
		image: '/assets/images/avatar/user-22.png',
		date: '06 Aug, 2024',
		name: 'Benjamin Scott',
		email: 'scott@example.com',
		phoneNumber: '+61 7 1234 5678',
		insurance: 'No',
		location: 'Belgium',
		treatmentType: 'Orthopedics',
		doctorName: 'Dr. Grace',
		gender: 'Male'
	},
	{
		image: '/assets/images/avatar/user-23.png',
		date: '07 Aug, 2024',
		name: 'Ava Green',
		email: 'ava@example.com',
		phoneNumber: '+81 50 1234 5678',
		insurance: 'No',
		location: 'Norway',
		treatmentType: 'Pediatrics',
		doctorName: 'Dr. Lucas',
		gender: 'Female'
	},
	{
		image: '/assets/images/avatar/user-24.png',
		date: '11 Aug, 2024',
		name: 'Mason Baker',
		email: 'baker@example.com',
		phoneNumber: '+86 20 1234 5678',
		insurance: 'No',
		location: 'Belgium',
		treatmentType: 'Gastroenterology',
		doctorName: 'Dr. Zoey',
		gender: 'Male'
	},
	{
		image: '/assets/images/avatar/user-25.png',
		date: '07 Feb, 2024',
		name: 'Isabella Nelson',
		email: 'nelson@example.com',
		phoneNumber: '+55 21 1234-5678',
		insurance: 'No',
		location: 'Poland',
		treatmentType: 'Oncology',
		doctorName: 'Dr. Mason',
		gender: 'Female'
	},
	{
		image: '/assets/images/avatar/user-26.png',
		date: '11 May, 2024',
		name: 'Elijah Carter',
		email: 'carter@example.com',
		phoneNumber: '+49 40 123456',
		insurance: 'No',
		location: 'Romania',
		treatmentType: 'Urology',
		doctorName: 'Dr. Lily',
		gender: 'Male'
	}
];
