export const badgeColors: Record<UI.BadgeVariantColor, string> = {
  "default-primary": "badge-primary",
  "default-purple": "badge-purple",
  "default-green": "badge-green",
  "default-red": "badge-red",
  "default-yellow": "badge-yellow",
  "default-sky": "badge-sky",
  "default-pink": "badge-pink",
  "default-indigo": "badge-indigo",
  "default-orange": "badge-orange",
  "default-gray": "badge-gray",
  "outline-primary": "badge-outline-primary",
  "outline-purple": "badge-outline-purple",
  "outline-green": "badge-outline-green",
  "outline-red": "badge-outline-red",
  "outline-yellow": "badge-outline-yellow",
  "outline-sky": "badge-outline-sky",
  "outline-pink": "badge-outline-pink",
  "outline-indigo": "badge-outline-indigo",
  "outline-orange": "badge-outline-orange",
  "outline-gray": "badge-outline-gray",
  "soft-primary": "badge-sub-primary",
  "soft-purple": "badge-sub-purple",
  "soft-green": "badge-sub-green",
  "soft-red": "badge-sub-red",
  "soft-yellow": "badge-sub-yellow",
  "soft-sky": "badge-sub-sky",
  "soft-pink": "badge-sub-pink",
  "soft-indigo": "badge-sub-indigo",
  "soft-orange": "badge-sub-orange",
  "soft-gray": "badge-sub-gray",
  "solid-primary": "badge-solid-primary",
  "solid-purple": "badge-solid-purple",
  "solid-green": "badge-solid-green",
  "solid-red": "badge-solid-red",
  "solid-yellow": "badge-solid-yellow",
  "solid-sky": "badge-solid-sky",
  "solid-pink": "badge-solid-pink",
  "solid-indigo": "badge-solid-indigo",
  "solid-orange": "badge-solid-orange",
  "solid-gray": "badge-solid-gray",
  "rounded-primary": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-primary",
  "rounded-purple": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-purple",
  "rounded-green": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-green",
  "rounded-red": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-red",
  "rounded-yellow": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-yellow",
  "rounded-sky": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-sky",
  "rounded-pink": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-pink",
  "rounded-indigo": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-indigo",
  "rounded-orange": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-orange",
  "rounded-gray": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-gray",
  "rounded-outline-primary": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-outline-primary",
  "rounded-outline-purple": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-outline-purple",
  "rounded-outline-green": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-outline-green",
  "rounded-outline-red": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-outline-red",
  "rounded-outline-yellow": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-outline-yellow",
  "rounded-outline-sky": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-outline-sky",
  "rounded-outline-pink": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-outline-pink",
  "rounded-outline-indigo": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-outline-indigo",
  "rounded-outline-orange": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-outline-orange",
  "rounded-outline-gray": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-outline-gray",
  "rounded-soft-primary": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-sub-primary",
  "rounded-soft-purple": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-sub-purple",
  "rounded-soft-green": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-sub-green",
  "rounded-soft-red": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-sub-red",
  "rounded-soft-yellow": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-sub-yellow",
  "rounded-soft-sky": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-sub-sky",
  "rounded-soft-pink": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-sub-pink",
  "rounded-soft-indigo": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-sub-indigo",
  "rounded-soft-orange": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-sub-orange",
  "rounded-soft-gray": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-sub-gray",
  "rounded-solid-primary": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-solid-primary",
  "rounded-solid-purple": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-solid-purple",
  "rounded-solid-green": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-solid-green",
  "rounded-solid-red": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-solid-red",
  "rounded-solid-yellow": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-solid-yellow",
  "rounded-solid-sky": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-solid-sky",
  "rounded-solid-pink": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-solid-pink",
  "rounded-solid-indigo": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-solid-indigo",
  "rounded-solid-orange": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-solid-orange",
  "rounded-solid-gray": "inline-block px-1.5 py-0.5 rounded-full text-11 border font-medium badge-solid-gray"
};