export const loaderColors: Record<UI.LoaderAnimationsColor, string> = {
  "spin-primary": " loader-spin loader-primary",
  "spin-purple": " loader-spin loader-purple",
  "spin-green": " loader-spin loader-green",
  "spin-red": " loader-spin loader-red",
  "spin-yellow": " loader-spin loader-yellow",
  "spin-sky": " loader-spin loader-sky",
  "spin-pink": " loader-spin loader-pink",
  "spin-indigo": " loader-spin loader-indigo",
  "spin-orange": " loader-spin loader-orange",
  "spin-light": " loader-spin loader-light",
  "spin-dark": " loader-spin loader-dark",
  "spin-2-primary": " modern-spin loader-primary",
  "spin-2-purple": " modern-spin loader-purple",
  "spin-2-green": " modern-spin loader-green",
  "spin-2-red": " modern-spin loader-red",
  "spin-2-yellow": " modern-spin loader-yellow",
  "spin-2-sky": " modern-spin loader-sky",
  "spin-2-pink": " modern-spin loader-pink",
  "spin-2-indigo": " modern-spin loader-indigo",
  "spin-2-orange": " modern-spin loader-orange",
  "spin-2-light": " modern-spin loader-light",
  "spin-2-dark": " modern-spin loader-dark",
  "bounce-primary": " animate-bounce loader-primary",
  "bounce-purple": " animate-bounce loader-purple",
  "bounce-green": " animate-bounce loader-green",
  "bounce-red": " animate-bounce loader-red",
  "bounce-yellow": " animate-bounce loader-yellow",
  "bounce-sky": " animate-bounce loader-sky",
  "bounce-pink": " animate-bounce loader-pink",
  "bounce-indigo": " animate-bounce loader-indigo",
  "bounce-orange": " animate-bounce loader-orange",
  "bounce-light": " animate-bounce loader-light",
  "bounce-dark": " animate-bounce loader-dark",
  "ping-primary": " animate-ping rounded-full loader-primary",
  "ping-purple": " animate-ping rounded-full loader-purple",
  "ping-green": " animate-ping rounded-full loader-green",
  "ping-red": " animate-ping rounded-full loader-red",
  "ping-yellow": " animate-ping rounded-full loader-yellow",
  "ping-sky": " animate-ping rounded-full loader-sky",
  "ping-pink": " animate-ping rounded-full loader-pink",
  "ping-indigo": " animate-ping rounded-full loader-indigo",
  "ping-orange": " animate-ping rounded-full loader-orange",
  "ping-light": " animate-ping rounded-full loader-light",
  "ping-dark": " animate-ping rounded-full loader-dark",
  "pulse-primary": " animate-pulse loader-primary",
  "pulse-purple": " animate-pulse loader-purple",
  "pulse-green": " animate-pulse loader-green",
  "pulse-red": " animate-pulse loader-red",
  "pulse-yellow": " animate-pulse loader-yellow",
  "pulse-sky": " animate-pulse loader-sky",
  "pulse-pink": " animate-pulse loader-pink",
  "pulse-indigo": " animate-pulse loader-indigo",
  "pulse-orange": " animate-pulse loader-orange",
  "pulse-light": " animate-pulse loader-light",
  "pulse-dark": " animate-pulse loader-dark"
};