export const progressColors: Record<UI.ProgressVariantColor, string> = {
	'default-': ' bg-default',
	'default-primary': ' bg-primary',
	'default-purple': ' bg-purple',
	'default-green': ' bg-green',
	'default-red': ' bg-red',
	'default-yellow': ' bg-yellow',
	'default-sky': ' bg-sky',
	'default-pink': ' bg-pink',
	'default-indigo': ' bg-indigo',
	'default-orange': ' bg-orange',
	'default-light': ' bg-light',
	'default-dark': ' bg-dark',
	'soft-': ' bg-soft',
	'soft-primary': ' bg-sub-primary',
	'soft-purple': ' bg-sub-purple',
	'soft-green': ' bg-sub-green',
	'soft-red': ' bg-sub-red',
	'soft-yellow': ' bg-sub-yellow',
	'soft-sky': ' bg-sub-sky',
	'soft-pink': ' bg-sub-pink',
	'soft-indigo': ' bg-sub-indigo',
	'soft-orange': ' bg-sub-orange',
	'soft-light': ' bg-sub-light',
	'soft-dark': ' bg-sub-dark'
};
