export const buttonColors: Record<UI.ButtonVariantColor, string> = {
  "default-primary": " btn-primary",
  "default-purple": " btn-purple",
  "default-green": " btn-green",
  "default-red": " btn-red",
  "default-yellow": " btn-yellow",
  "default-sky": " btn-sky",
  "default-pink": " btn-pink",
  "default-indigo": " btn-indigo",
  "default-orange": " btn-orange",
  "default-light": " bg-transparent text-gray-500 border-gray-200 hover:bg-gray-200 hover:text-gray-500 hover:border-gray-200 focus:bg-gray-200 focus:text-gray-500 focus:border-gray-200",
  "default-dark": " btn-dark",
  "outline-primary": " btn-outline-primary",
  "outline-purple": " btn-outline-purple",
  "outline-green": " btn-outline-green",
  "outline-red": " btn-outline-red",
  "outline-yellow": " btn-outline-yellow",
  "outline-sky": " btn-outline-sky",
  "outline-pink": " btn-outline-pink",
  "outline-indigo": " btn-outline-indigo",
  "outline-orange": " btn-outline-orange",
  "outline-light": " bg-transparent text-gray-500 border-gray-200 hover:bg-gray-200 hover:text-gray-500 hover:border-gray-200 focus:bg-gray-200 focus:text-gray-500 focus:border-gray-200",
  "outline-dark": " btn-outline-dark",
  "soft-primary": " btn-sub-primary",
  "soft-purple": " btn-sub-purple",
  "soft-green": " btn-sub-green",
  "soft-red": " btn-sub-red",
  "soft-yellow": " btn-sub-yellow",
  "soft-sky": " btn-sub-sky",
  "soft-pink": " btn-sub-pink",
  "soft-indigo": " btn-sub-indigo",
  "soft-orange": " btn-sub-orange",
  "soft-light": " bg-transparent border-gray-50 text-gray-500 hover:bg-gray-100 hover:text-gray-500 focus:text-gray-500 focus:bg-gray-100",
  "soft-dark": " btn-sub-dark",
  "3d-primary": " btn-sub-primary",
  "3d-purple": " btn-sub-purple",
  "3d-green": " btn-sub-green",
  "3d-red": " btn-sub-red",
  "3d-yellow": " btn-sub-yellow",
  "3d-sky": " btn-sub-sky",
  "3d-pink": " btn-sub-pink",
  "3d-indigo": " btn-sub-indigo",
  "3d-orange": " btn-sub-orange",
  "3d-light": " btn-3d-light bg-gray-100 text-gray-500 hover:bg-gray-100 focus:bg-gray-200",
  "3d-dark": " btn-sub-dark",
  "dashed-primary": " btn-dashed-primary border-dashed",
  "dashed-purple": " btn-dashed-purple border-dashed",
  "dashed-green": " btn-dashed-green border-dashed",
  "dashed-red": " btn-dashed-red border-dashed",
  "dashed-yellow": " btn-dashed-yellow border-dashed",
  "dashed-sky": " btn-dashed-sky border-dashed",
  "dashed-pink": " btn-dashed-pink border-dashed",
  "dashed-indigo": " btn-dashed-indigo border-dashed",
  "dashed-orange": " btn-dashed-orange border-dashed",
  "dashed-light": " bg-transparent text-gray-500 border-gray-200 hover:bg-gray-50 hover:text-gray-500 hover:border-gray-200 focus:bg-gray-50 focus:text-gray-500 focus:border-gray-200 border-dashed",
  "dashed-dark": " btn-dashed-dark border-dashed",
  "active-primary": " btn-active-primary border-dashed",
  "active-purple": " btn-active-purple border-dashed",
  "active-green": " btn-active-green border-dashed",
  "active-red": " btn-active-red border-dashed",
  "active-yellow": " btn-active-yellow border-dashed",
  "active-sky": " btn-active-sky border-dashed",
  "active-pink": " btn-active-pink border-dashed",
  "active-indigo": " btn-active-indigo border-dashed",
  "active-orange": " btn-active-orange border-dashed",
  "active-light": " bg-transparent text-gray-500 border-gray-200 hover:bg-gray-200 hover:text-gray-500 hover:border-gray-200 focus:bg-gray-200 focus:text-gray-500 focus:border-gray-200",
  "active-dark": " btn-active-dark border-dashed"
};